#!/usr/bin/env python3
"""FDS Principles Evaluator — hard gate on engagement reply alignment.

Every reply passes through this 5th evaluator before posting.
Score < 0.70 = auto-reject (hard gate, never overridden by consensus).

FDS Principles:
  1. "Your data is you" — individual data sovereignty is non-negotiable
  2. "Our data is us" — collective/community data rights matter
  3. Privacy is architecture, not policy — structural solutions beat compliance theater
  4. Open, interoperable, fair data economy — closed silos are the problem

Usage:
    from principles_evaluator import evaluate_principles, PRINCIPLES_THRESHOLD
    result = evaluate_principles(draft_reply, target_content, target_author)
    if result.score < PRINCIPLES_THRESHOLD:
        # Auto-reject
        print(f"Principles gate failed: {result.feedback}")
"""

import os
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

DATA_DIR = Path(os.environ.get("DATACORE_ROOT", os.path.expanduser("~/Data")))

PRINCIPLES_THRESHOLD = 0.70  # Hard gate — replies below this are auto-rejected

PRINCIPLES_PROMPT = """You are evaluating a tweet reply for @FairDataSociety against the Fair Data Society principles.

FDS Principles:
1. "Your data is you" — individual data sovereignty is non-negotiable. People own their data, full stop.
2. "Our data is us" — collective/community data rights matter. Data generated by communities should benefit those communities.
3. Privacy is architecture, not policy — structural solutions beat compliance theater. Real privacy is built into systems, not promised in documents.
4. Open, interoperable, fair data economy — closed silos are the problem. Open protocols and standards enable a fair ecosystem.

Score 0.0–1.0 against these principles:

1.0 = Reply actively supports at least one principle explicitly or implicitly
0.8 = Reply is strongly aligned — argues for individual rights, structural privacy, or open systems
0.7 = Reply is neutral, doesn't contradict principles (acceptable — not every reply needs to preach)
0.5 = Reply implicitly endorses centralization, compliance theater, or data commodification
0.3 = Reply praises Big Tech "privacy" features as actual solutions, or endorses surveillance capitalism
0.0 = Reply directly contradicts FDS principles

AUTOMATIC FAIL (score ≤ 0.3) examples:
- Praising Google Privacy Sandbox or Apple Privacy Label as meaningful solutions (compliance theater)
- Framing GDPR compliance as "solving" the problem when it's just paperwork
- Endorsing VC-funded data monetization as fair to users
- Treating centralized AI training on user data as acceptable
- Promoting token/airdrop angle that commodifies personal data
- "Just use a VPN" type thinking that mistakes tools for structural change

AUTOMATIC PASS (score ≥ 0.8) examples:
- Supporting data portability, interoperability, or open standards
- Arguing for encryption-by-default, zero-knowledge, or decentralized storage
- Pointing out that policy without architecture is theater
- Defending collective data rights or community ownership
- Critiquing platform lock-in or surveillance capitalism

NEUTRAL (score 0.7) examples:
- Extending a conversation about journalism safety without mentioning FDS
- Asking a question that advances understanding of privacy issues
- Agreeing with someone's frustration about data breaches
- Brief "this" style agreements to privacy-conscious posts

The evaluator cares about alignment, not about whether FDS is mentioned.
Most good replies will score 0.7 (neutral/aligned) — that's fine.

You MUST respond with ONLY this YAML block:
```yaml
evaluator: principles
score: <number between 0.0 and 1.0>
feedback: "<one sentence — what specifically passes or fails the principles check>"
```

Nothing else."""

EVALUATION_TEMPLATE = """# Principles Evaluation

{principles_prompt}

## Target tweet being replied to
Author: {target_author}
Content: {target_content}

## Draft reply to evaluate
{draft_reply}

Evaluate this reply against FDS principles."""


@dataclass
class PrinciplesResult:
    score: float
    feedback: str
    passed: bool

    @property
    def gate_label(self) -> str:
        if self.passed:
            return f"PASS ({self.score:.0%})"
        return f"FAIL ({self.score:.0%}) — {self.feedback[:60]}"


def evaluate_principles(
    draft_reply: str,
    target_content: str,
    target_author: str,
    model: str = "sonnet",
) -> PrinciplesResult:
    """Run the FDS principles gate on a draft reply.

    Uses Sonnet — same model as quality evaluators. Principles alignment
    requires genuine understanding of nuanced framing, not just keyword matching.

    Args:
        draft_reply: The draft tweet text
        target_content: The tweet content being replied to
        target_author: Who we're replying to
        model: Claude model (haiku for speed)

    Returns:
        PrinciplesResult with score, feedback, and passed (score >= 0.70)
    """
    prompt = EVALUATION_TEMPLATE.format(
        principles_prompt=PRINCIPLES_PROMPT,
        target_author=target_author,
        target_content=target_content[:300],
        draft_reply=draft_reply,
    )

    env = {k: v for k, v in os.environ.items() if not k.startswith("CLAUDE")}
    env["PATH"] = os.environ.get("PATH", "/usr/local/bin:/usr/bin:/bin")
    env["HOME"] = os.environ.get("HOME", str(Path.home()))

    try:
        result = subprocess.run(
            [
                "claude", "-p",
                "--model", model,
                "--output-format", "text",
                "--no-session-persistence",
                "--max-turns", "1",
            ],
            input=prompt,
            capture_output=True,
            text=True,
            cwd=str(DATA_DIR),
            env=env,
            timeout=30,
        )

        if result.returncode != 0:
            # Default to pass on error — fail open (principles gate shouldn't block on timeouts)
            return PrinciplesResult(score=0.7, feedback="Evaluator error — defaulting to pass", passed=True)

        return _parse_result(result.stdout)

    except subprocess.TimeoutExpired:
        return PrinciplesResult(score=0.7, feedback="Timed out — defaulting to pass", passed=True)
    except Exception as e:
        return PrinciplesResult(score=0.7, feedback=f"Error: {str(e)[:60]}", passed=True)


def _parse_result(output: str) -> PrinciplesResult:
    """Parse YAML score and feedback from evaluator output."""
    yaml_match = re.search(r'```yaml\s*(.*?)\s*```', output, re.DOTALL)
    text = yaml_match.group(1) if yaml_match else output

    score_match = re.search(r'score:\s*([\d.]+)', text)
    score = float(score_match.group(1)) if score_match else 0.7
    score = max(0.0, min(1.0, score))

    feedback_match = re.search(r'feedback:\s*["\']?(.+?)["\']?\s*(?:\n|$)', text, re.DOTALL)
    feedback = feedback_match.group(1).strip() if feedback_match else "No feedback"

    return PrinciplesResult(
        score=score,
        feedback=feedback,
        passed=score >= PRINCIPLES_THRESHOLD,
    )


if __name__ == "__main__":
    """Quick test — run against sample replies."""
    import sys

    test_cases = [
        # Should PASS
        ("Policy changes. Architecture doesn't.",
         "GDPR is finally being enforced against Meta",
         "@someregulator"),
        # Should PASS (neutral agreement)
        ("This.",
         "We need to stop treating data privacy as a compliance checkbox",
         "@privacyadvocate"),
        # Should FAIL (compliance theater endorsement)
        ("Google's Privacy Sandbox is a solid step forward for the ecosystem.",
         "What should replace third-party cookies?",
         "@adtech_person"),
        # Should PASS (open standards)
        ("And that's the case for open protocols over platform lock-in.",
         "ActivityPub federation is underrated",
         "@fediverse_dev"),
    ]

    print("Principles Evaluator Test\n" + "=" * 40)
    for draft, target, author in test_cases:
        result = evaluate_principles(draft, target, author)
        status = "PASS" if result.passed else "FAIL"
        print(f"\n[{status}] {result.score:.0%} — \"{draft[:60]}\"")
        print(f"  → {result.feedback}")

    sys.exit(0)
